import Foundation

/// Provides safe bundle and binary resource discovery for ClashBar.
///
/// **Why this locator is required:**
/// When packaging a SwiftPM executable into a standard macOS `.app` bundle (via `package_app.sh`),
/// SPM's autogenerated `Bundle.module` looks for `ClashBar_ClashBar.bundle` directly inside `Bundle.main.bundleURL`
/// (`ClashBar.app/ClashBar_ClashBar.bundle`).
/// However, standard macOS bundle layout requires resources to reside inside
/// `ClashBar.app/Contents/Resources/ClashBar_ClashBar.bundle`. Calling raw `Bundle.module` in a packaged app
/// triggers a `fatalError` and crashes immediately.
///
/// This locator safely checks `Bundle.main.resourceURL` first, preventing production crashes, while also
/// providing helper binary root locations (`Contents/Helpers`, `Contents/MacOS`) for external core resolution.
enum AppResourceBundleLocator {
    private static let moduleBundleName = "ClashBar_ClashBar.bundle"

    static func moduleBundle() -> Bundle? {
        if let resourceURL = Bundle.main.resourceURL,
           let bundle = Bundle(url: resourceURL.appendingPathComponent(self.moduleBundleName, isDirectory: true))
        {
            return bundle
        }
        if let bundle = Bundle(url: Bundle.main.bundleURL.appendingPathComponent(
            self.moduleBundleName,
            isDirectory: true))
        {
            return bundle
        }
        return Bundle.module
    }

    static func candidateBundles() -> [Bundle] {
        var bundles: [Bundle] = []
        if let module = self.moduleBundle() {
            bundles.append(module)
        }
        if !bundles.contains(where: { $0.bundleURL == Bundle.main.bundleURL }) {
            bundles.append(Bundle.main)
        }
        return bundles
    }

    static func candidateResourceRoots() -> [URL] {
        self.candidateBundles().compactMap(\.resourceURL)
    }

    static func candidateBinaryRoots() -> [URL] {
        var roots: [URL] = []
        let main = Bundle.main.bundleURL
        roots.append(main.appendingPathComponent("Contents/Helpers", isDirectory: true))
        roots.append(main.appendingPathComponent("Contents/MacOS", isDirectory: true))
        roots.append(contentsOf: self.candidateResourceRoots())
        return roots
    }

    static func bundledDefaultConfigURL(fileManager: FileManager = .default) -> URL? {
        let candidateRelativePaths = [
            "ConfigTemplates/ClashBar.yaml",
            "Resources/ConfigTemplates/ClashBar.yaml",
            "ClashBar.yaml",
        ]
        for root in self.candidateResourceRoots() {
            for relativePath in candidateRelativePaths {
                let candidate = root.appendingPathComponent(relativePath, isDirectory: false)
                if fileManager.fileExists(atPath: candidate.path) {
                    return candidate
                }
            }
        }
        return nil
    }
}

extension Bundle {
    /// Safe application resource bundle that falls back to `Bundle.module` in development,
    /// avoiding fatal errors in packaged standalone macOS application bundles.
    static var appResources: Bundle {
        AppResourceBundleLocator.moduleBundle() ?? .module
    }
}
